import mongoose from "mongoose";
import dotenv from "dotenv";
import MasterData from "../models/masterDataModel.js";

dotenv.config();

const seedData = [
  { type: "category", label: "Retail", value: "retail" },
  { type: "category", label: "Wholesale", value: "wholesale" },
  { type: "category", label: "Manufacturing", value: "manufacturing" },
  { type: "category", label: "Service Provider", value: "service" },
  { type: "category", label: "E-Commerce", value: "ecommerce" },
  { type: "category", label: "Import/Export", value: "importexport" },
  { type: "category", label: "Agriculture", value: "agriculture" },
  { type: "category", label: "IT & Software", value: "it" },
  { type: "category", label: "Healthcare", value: "healthcare" },
  { type: "category", label: "Construction", value: "construction" },
  { type: "category", label: "Real Estate", value: "realestate" },
  { type: "category", label: "Education", value: "education" },
  { type: "category", label: "Hospitality", value: "hospitality" },
  { type: "category", label: "Transport & Logistics", value: "transport" },
  { type: "category", label: "Banking & Finance", value: "banking" },
  { type: "category", label: "Consulting", value: "consulting" },
  { type: "category", label: "Non-Profit", value: "nonprofit" },
  { type: "category", label: "Freelance", value: "freelance" },
  { type: "category", label: "Mining", value: "mining" },
  { type: "category", label: "Energy", value: "energy" },

  { type: "businessType", label: "Sole Proprietorship", value: "soleprop" },
  { type: "businessType", label: "Partnership Firm", value: "partnership" },
  {
    type: "businessType",
    label: "Limited Liability Partnership (LLP)",
    value: "llp",
  },
  { type: "businessType", label: "Private Limited Company", value: "pvtltd" },
  { type: "businessType", label: "Public Limited Company", value: "publicltd" },
  { type: "businessType", label: "One Person Company (OPC)", value: "opc" },
  { type: "businessType", label: "Hindu Undivided Family (HUF)", value: "huf" },
  { type: "businessType", label: "Co-operative Society", value: "coop" },
  {
    type: "businessType",
    label: "Non-Government Organisation (NGO)",
    value: "ngo",
  },
  { type: "businessType", label: "Trust", value: "trust" },
  {
    type: "businessType",
    label: "Branch Office (Foreign Company)",
    value: "branch",
  },
  { type: "businessType", label: "Subsidiary Company", value: "subsidiary" },
  { type: "businessType", label: "Joint Venture", value: "jointventure" },
  {
    type: "businessType",
    label: "Unregistered Business",
    value: "unregistered",
  },

  { type: "country", label: "India", value: "IN" },
  { type: "country", label: "United States", value: "US" },
  { type: "country", label: "United Kingdom", value: "GB" },
  { type: "country", label: "Germany", value: "DE" },
  { type: "country", label: "Japan", value: "JP" },
  { type: "country", label: "Australia", value: "AU" },
  { type: "country", label: "Canada", value: "CA" },
  { type: "country", label: "Singapore", value: "SG" },
  { type: "country", label: "United Arab Emirates", value: "AE" },
  { type: "country", label: "France", value: "FR" },
  { type: "country", label: "China", value: "CN" },
  { type: "country", label: "Brazil", value: "BR" },
  { type: "country", label: "South Africa", value: "ZA" },
  { type: "country", label: "Saudi Arabia", value: "SA" },
  { type: "country", label: "Malaysia", value: "MY" },
  { type: "country", label: "Netherlands", value: "NL" },
  { type: "country", label: "Switzerland", value: "CH" },
  { type: "country", label: "Hong Kong", value: "HK" },
  { type: "country", label: "Sweden", value: "SE" },
  { type: "country", label: "Mexico", value: "MX" },

  { type: "department", label: "Sales", value: "sales" },
  { type: "department", label: "Customer Support", value: "support" },
  { type: "department", label: "Finance & Accounts", value: "finance" },
  { type: "department", label: "Compliance", value: "compliance" },
  { type: "department", label: "Legal", value: "legal" },
  { type: "department", label: "Risk Management", value: "risk" },
  { type: "department", label: "Operations", value: "operations" },
  { type: "department", label: "IT & Security", value: "it" },
  { type: "department", label: "Business Development", value: "businessdev" },
  { type: "department", label: "Onboarding", value: "onboarding" },
  {
    type: "department",
    label: "Relationship Management",
    value: "relationship",
  },
  { type: "department", label: "Administration", value: "admin" },
  { type: "department", label: "Internal Audit", value: "audit" },
  { type: "department", label: "Marketing", value: "marketing" },
  { type: "department", label: "Human Resources", value: "hr" },

  { type: "salesPerson", label: "Rajesh Kumar", value: "rajesh" },
  { type: "salesPerson", label: "Priya Singh", value: "priya" },
  { type: "salesPerson", label: "Amit Sharma", value: "amit" },
  { type: "salesPerson", label: "Sneha Patel", value: "sneha" },
  { type: "salesPerson", label: "Vikram Malhotra", value: "vikram" },
  { type: "salesPerson", label: "Neha Gupta", value: "neha" },
  { type: "salesPerson", label: "Alok Joshi", value: "alok" },
  { type: "salesPerson", label: "Deepika Reddy", value: "deepika" },
  { type: "salesPerson", label: "Karan Mehta", value: "karan" },
  { type: "salesPerson", label: "Anjali Iyer", value: "anjali" },
  { type: "salesPerson", label: "Rahul Desai", value: "rahul" },
  { type: "salesPerson", label: "Sonia Chatterjee", value: "sonia" },
  { type: "salesPerson", label: "Mohammed Khan", value: "mohammed" },
  { type: "salesPerson", label: "Nidhi Agarwal", value: "nidhi" },
  { type: "salesPerson", label: "Ishaan Kapoor", value: "ishaan" },

  { type: "assistantSalesPerson", label: "Mike Ross", value: "mike" },
  { type: "assistantSalesPerson", label: "Sarah Jones", value: "sarah" },
  { type: "assistantSalesPerson", label: "David Brown", value: "david" },
  { type: "assistantSalesPerson", label: "Emily Chen", value: "emily" },
  { type: "assistantSalesPerson", label: "Arun Verma", value: "arun" },
  { type: "assistantSalesPerson", label: "Lisa Thomas", value: "lisa" },
  { type: "assistantSalesPerson", label: "Sanjay Pillai", value: "sanjay" },
  { type: "assistantSalesPerson", label: "Maria Garcia", value: "maria" },
  { type: "assistantSalesPerson", label: "Anil Yadav", value: "anil" },
  { type: "assistantSalesPerson", label: "Jessica Lee", value: "jessica" },
  { type: "assistantSalesPerson", label: "Ravi Shastri", value: "ravi" },
  { type: "assistantSalesPerson", label: "Olivia Martinez", value: "olivia" },
  { type: "assistantSalesPerson", label: "Vijay Singh", value: "vijay" },
  { type: "assistantSalesPerson", label: "Sophia Williams", value: "sophia" },
  { type: "assistantSalesPerson", label: "Preeti Nair", value: "preeti" },

  { type: "currencies", label: "Indian Rupee (₹)", value: "inr" },
  { type: "currencies", label: "US Dollar ($)", value: "usd" },
  { type: "currencies", label: "Euro (€)", value: "eur" },
  { type: "currencies", label: "British Pound (£)", value: "gbp" },
  { type: "currencies", label: "Japanese Yen (¥)", value: "jpy" },
  { type: "currencies", label: "Australian Dollar (A$)", value: "aud" },
  { type: "currencies", label: "Canadian Dollar (C$)", value: "cad" },
  { type: "currencies", label: "Singapore Dollar (S$)", value: "sgd" },
  { type: "currencies", label: "Swiss Franc (CHF)", value: "chf" },
  { type: "currencies", label: "Hong Kong Dollar (HK$)", value: "hkd" },
  { type: "currencies", label: "Chinese Yuan (¥)", value: "cny" },
  { type: "currencies", label: "UAE Dirham (د.إ)", value: "aed" },
  { type: "currencies", label: "Saudi Riyal (﷼)", value: "sar" },
  { type: "currencies", label: "Swedish Krona (kr)", value: "sek" },
  { type: "currencies", label: "Norwegian Krone (kr)", value: "nok" },
  { type: "currencies", label: "Danish Krone (kr)", value: "dkk" },
  { type: "currencies", label: "Polish Złoty (zł)", value: "pln" },
  { type: "currencies", label: "Turkish Lira (₺)", value: "try" },
  { type: "currencies", label: "South African Rand (R)", value: "zar" },
  { type: "currencies", label: "Russian Ruble (₽)", value: "rub" },
  { type: "currencies", label: "Brazilian Real (R$)", value: "brl" },
  { type: "currencies", label: "Mexican Peso ($)", value: "mxn" },
  { type: "currencies", label: "Thai Baht (฿)", value: "thb" },
  { type: "currencies", label: "Malaysian Ringgit (RM)", value: "myr" },
  { type: "currencies", label: "Indonesian Rupiah (Rp)", value: "idr" },

  { type: "dayTerms", label: "1 day", value: "1" },
  { type: "dayTerms", label: "7 days", value: "7" },
  { type: "dayTerms", label: "30 days", value: "30" },
  { type: "dayTerms", label: "90 days", value: "90" },
  { type: "dayTerms", label: "365 days", value: "365" },

  { type: "parties", label: "Not Applicable", value: "na" },
  { type: "parties", label: "Bharatiya Janata Party (BJP)", value: "bjp" },
  { type: "parties", label: "Indian National Congress (INC)", value: "inc" },
  { type: "parties", label: "Aam Aadmi Party (AAP)", value: "aap" },
  { type: "parties", label: "Shiv Sena", value: "shivsena" },
  {
    type: "parties",
    label: "All India Trinamool Congress (TMC)",
    value: "tmc",
  },
  { type: "parties", label: "Bahujan Samaj Party (BSP)", value: "bsp" },
  {
    type: "parties",
    label: "Communist Party of India (Marxist) (CPI(M))",
    value: "cpim",
  },
  { type: "parties", label: "Telugu Desam Party (TDP)", value: "tdp" },
  { type: "parties", label: "Janata Dal (United) (JD(U))", value: "jdu" },
  { type: "parties", label: "Nationalist Congress Party (NCP)", value: "ncp" },
  { type: "parties", label: "Samajwadi Party (SP)", value: "sp" },
  { type: "parties", label: "Dravida Munnetra Kazhagam (DMK)", value: "dmk" },
  {
    type: "parties",
    label: "All India Anna Dravida Munnetra Kazhagam (AIADMK)",
    value: "aiadmk",
  },
  { type: "parties", label: "Rashtriya Janata Dal (RJD)", value: "rjd" },
  { type: "parties", label: "Biju Janata Dal (BJD)", value: "bjd" },
  { type: "parties", label: "Telangana Rashtra Samithi (TRS)", value: "trs" },
  { type: "parties", label: "Lok Janshakti Party (LJP)", value: "ljp" },
  { type: "parties", label: "Republican Party (USA)", value: "republican" },
  { type: "parties", label: "Democratic Party (USA)", value: "democrat" },
  { type: "parties", label: "Conservative Party (UK)", value: "conservative" },
  { type: "parties", label: "Labour Party (UK)", value: "labour" },

  { type: "brokers", label: "Direct Client (No Broker)", value: "direct" },
  {
    type: "brokers",
    label: "Motilal Oswal Financial Services",
    value: "motilal",
  },
  { type: "brokers", label: "ICICI Securities", value: "icicidirect" },
  { type: "brokers", label: "HDFC Securities", value: "hdfcsec" },
  { type: "brokers", label: "Sharekhan", value: "sharekhan" },
  { type: "brokers", label: "Axis Direct", value: "axisdirect" },
  { type: "brokers", label: "Kotak Securities", value: "kotaksec" },
  { type: "brokers", label: "Angel Broking", value: "angel" },
  { type: "brokers", label: "Zerodha", value: "zerodha" },
  { type: "brokers", label: "Upstox", value: "upstox" },
  { type: "brokers", label: "5Paisa", value: "5paisa" },
  { type: "brokers", label: "Edelweiss Broking", value: "edelweiss" },
  { type: "brokers", label: "IIFL Securities", value: "iifl" },
  { type: "brokers", label: "Geojit Financial Services", value: "geojit" },
  { type: "brokers", label: "SBI Capital Markets", value: "sbicap" },
  { type: "brokers", label: "Reliance Securities", value: "reliancesec" },
  {
    type: "brokers",
    label: "Anand Rathi Share and Stock Brokers",
    value: "anandrathi",
  },
  { type: "brokers", label: "Prabhudas Lilladher", value: "pl" },
  { type: "brokers", label: "JM Financial", value: "jm" },
  { type: "brokers", label: "DSP Merrill Lynch", value: "dsp" },
  { type: "brokers", label: "Morgan Stanley India", value: "morganstanley" },
  { type: "brokers", label: "Credit Suisse", value: "creditsuisse" },
  { type: "brokers", label: "Goldman Sachs", value: "goldmansachs" },

  {
    type: "terms",
    label:
      "I agree to the terms and conditions, privacy policy, and consent to data verification.",
    value: "full_consent",
  },

  { type: "roles", label: "Applicant", value: "applicant" },
  { type: "roles", label: "Individual", value: "individual" },
  { type: "roles", label: "Business Representative", value: "business_rep" },
  { type: "roles", label: "Legal Guardian", value: "guardian" },
  { type: "roles", label: "Authorized Signatory", value: "signatory" },

  { type: "locations", label: "Andhra Pradesh", value: "andhra_pradesh" },
  { type: "locations", label: "Arunachal Pradesh", value: "arunachal_pradesh" },
  { type: "locations", label: "Assam", value: "assam" },
  { type: "locations", label: "Bihar", value: "bihar" },
  { type: "locations", label: "Chhattisgarh", value: "chhattisgarh" },
  { type: "locations", label: "Goa", value: "goa" },
  { type: "locations", label: "Gujarat", value: "gujarat" },
  { type: "locations", label: "Haryana", value: "haryana" },
  { type: "locations", label: "Himachal Pradesh", value: "himachal_pradesh" },
  { type: "locations", label: "Jharkhand", value: "jharkhand" },
  { type: "locations", label: "Karnataka", value: "karnataka" },
  { type: "locations", label: "Kerala", value: "kerala" },
  { type: "locations", label: "Madhya Pradesh", value: "madhya_pradesh" },
  { type: "locations", label: "Maharashtra", value: "maharashtra" },
  { type: "locations", label: "Manipur", value: "manipur" },
  { type: "locations", label: "Meghalaya", value: "meghalaya" },
  { type: "locations", label: "Mizoram", value: "mizoram" },
  { type: "locations", label: "Nagaland", value: "nagaland" },
  { type: "locations", label: "Odisha", value: "odisha" },
  { type: "locations", label: "Punjab", value: "punjab" },
  { type: "locations", label: "Rajasthan", value: "rajasthan" },
  { type: "locations", label: "Sikkim", value: "sikkim" },
  { type: "locations", label: "Tamil Nadu", value: "tamil_nadu" },
  { type: "locations", label: "Telangana", value: "telangana" },
  { type: "locations", label: "Tripura", value: "tripura" },
  { type: "locations", label: "Uttar Pradesh", value: "uttar_pradesh" },
  { type: "locations", label: "Uttarakhand", value: "uttarakhand" },
  { type: "locations", label: "West Bengal", value: "west_bengal" },

  { type: "addressTypes", label: "Permanent", value: "permanent" },
  { type: "addressTypes", label: "Current", value: "current" },
  { type: "addressTypes", label: "Office", value: "office" },
  { type: "addressTypes", label: "Home", value: "home" },
  { type: "addressTypes", label: "Billing", value: "billing" },
  { type: "addressTypes", label: "Shipping", value: "shipping" },
  { type: "addressTypes", label: "Temporary", value: "temporary" },

  { type: "countryAddress", label: "India", value: "india" },
  { type: "countryAddress", label: "United Arab Emirates", value: "uae" },
  { type: "countryAddress", label: "United States", value: "usa" },
];
const seed = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    await MasterData.deleteMany();
    await MasterData.insertMany(seedData);
    console.log("✅ Master data seeded");
    process.exit();
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
};

seed();
